name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOST_SSH_KEY }}
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST_USERNAME@crimea-rentacar.ru" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -avz --delete --exclude='.git*' ./ $HOST_USERNAME@crimea-rentacar.ru:/var/www/u0374744/data/www/crimea-rentacar.ru
