name: Deploy to Server

on:
  push:
    branches:
      - main  # Укажите нужную ветку, например main или master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOST_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${secrets.HOST_USERNAME}@crimea-rentacar.ru >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          USERNAME: ${{ secrets.HOST_USERNAME }}
        run: |
          rsync -avz --delete --exclude='.git*' ./ ${USERNAME}@crimea-rentacar.ru:/var/www/u0374744/data/www/crimea-rentacar.ru
